---
title: "Explore Ice Bears"
output: html_notebook
---

# Exploring Ice Bears

### Reproductive Status

```{r}
library(sf)
library(dplyr)
library(sp)
library(ggplot2)
library(tmap)

rm(list = ls())

# load data

load('all_v2.RData')
setwd('C:/Users/akell/Documents/ArcGIS') # GIS data

# ------------------------------------------------------------------------------------- #

# projection

albers.proj <- CRS("+proj=aea +lat_1=55 +lat_2=65 +lat_0=50 +lon_0=-154 +x_0=0 +y_0=0 +ellps=GRS80 +datum=NAD83 +units=m +no_defs") # Albers Equal Area Conic (same as ArcMap doc)

# Function to turn df into sf (cannot droplevels in sf object so always need to start w df)

DFtoSF <- function(df) {
  df <- droplevels(df)
  sf.wgs <- st_as_sf(df, coords = c('gps_lon', 'gps_lat'), crs = 4326, dim = 'XY')
  sf.alb <- st_transform(sf.wgs, albers.proj)
  return(sf.alb)
}
```

# Denning Bears (OWS while they are pregnant)

```{r}
#Denning Bears
den <- subset(all.v2, DenYr == 1 & ows == 1)
bears <- DFtoSF(den)

# tmap

tmap_mode("view") # in view mode, land fills in

tm_shape(bears) +
  tm_symbols(col = "month", popup.vars = "year", "month", "day") +
  tm_facets(by = "animal") +
  tmap_options(limits = c(facets.view = 20))
  
```

# Coys

```{r}

coy <- subset(all.v2, coy ==1 & ows == 1)
coy <- (DFtoSF(coy))

tm_shape(coy) +
  tm_symbols(col = "month", popup.vars = c("year", "month")) +
  tm_facets(by = "animal") +
  tm_shape(bone) + tm_symbols(col = "green") +
  tmap_options(limits = c(facets.view = 8))
```

# Yearling

```{r}
yearling <- subset(all.v2, yearling == 1 & ows ==1)
yearling <- DFtoSF(yearling)

tm_shape(yearling) +
  tm_symbols(col = "month", popup.vars = c("year", "month", "day")) +
  tm_shape(bone) +
  tm_dots(col = "green", size = 0.08, legend.show = TRUE)
```


# Ice Bears

```{r}

ice <- subset(all.v2, yearling == 0 & coy == 0 & DenYr == 0 & ows == 1 & land_bear_ows == 0)

noData <- ice %>% # remove bears with < 100 data points
  add_count(id) %>%
  filter(n < 100)

ice <- anti_join(ice, noData)

# function to subset ice df to view individual ice bears
viewPB <- function(bear){ 
  pb <- filter(ice, id == bear)
  pb <- DFtoSF(pb)
  map <- tm_shape(pb) +
    tm_symbols(col = "month", popup.vars = c("year", "month", "day"))
  return(map)
  
}

#viewPB('pb_20479.2006') # view individual bear
```

# View all ice bears

```{r}
# View all ice bears

ice <- DFtoSF(ice)

tm_shape(ice) +
  tm_symbols(col = "month", popup.vars = c("year", "month", "day")) +
  tmap_options(limits = c(facets.view = 105)) +
  tm_facets("id", free.coords = TRUE)

```










