---
title: "Plots"
author: "Annie Kellner"
date: "11/4/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Null model 

```{r}
# Survival curve 

distSpeed3 <- coxph(Surv(tstart, tstop, migrate) ~ Dist2land_3davg + Windspeed_3davg, cluster = animal, data = cox_tdc)

surv_curve <- survfit(Surv(tstart, tstop, migrate) ~ Dist2land_3davg + Windspeed_3davg, cluster = animal, data = cox_tdc)   
fit_data <- data.frame(cbind(null_fit$time,null_fit$surv,null_fit$cumhaz,null_fit$upper,null_fit$lower))
names(fit_data) <- c("time","surv","cumhaz","upperCI","lowerCI")

ggplot(data=NULL) +
  geom_line(data=fit_data,aes(x=time, y=surv),colour="black",linetype="solid",size=1) +
  geom_line(data=fit_data,aes(x=time, y=upperCI),colour="black",linetype="dashed",size=.5) +
  geom_line(data=fit_data,aes(x=time, y=lowerCI),colour="black",linetype="dashed",size=.5) +
  #scale_x_continuous(breaks=seq(0,480,120)) +
  #scale_y_continuous(breaks=seq(0,1,.25)) +
 # expand_limits(x=c(0,480),y=c(0,1)) +
  xlab("") + ylab("Survival Function") +
theme_classic() +
theme(axis.line.x = element_line(color = "black"),
      axis.line.y = element_line(color = "black"))

# Cumulative hazard

ggplot(data=NULL) +
  geom_line(data=null_data,aes(x=time, y=cumhaz),colour="black",linetype="solid",size=1) +
  #scale_x_continuous(breaks=seq(0,480,120)) +
 # scale_y_continuous(breaks=seq(0,1,.25)) +
  #expand_limits(x=c(0,480),y=c(0,1)) +
  xlab("Ordinal Day") + ylab("Cumulative Hazard Function") +
theme_classic() +
theme(axis.line.x = element_line(color = "black"),
      axis.line.y = element_line(color = "black"))

```

# Plot cumulative hazard for whole model

```{r}

modelfit <- survfit(Surv(tstart, tstop, start.swim) ~ Windspeed + SICsq, cluster = animal, data = cox_tdc)
print(modelfit)
summary(modelfit)

modeldata <- data.frame(cbind(modelfit$time,modelfit$surv,modelfit$cumhaz,modelfit$upper,modelfit$lower))

cumhaz <- modeldata %>%
  group_by(time) %>%
  summarize(mean_cumhaz = mean(cumhaz))

ggplot(data=NULL) +
  geom_line(data=cumhaz,aes(x=time, y=mean_cumhaz),colour="black",linetype="solid",size=1) +
  #scale_x_continuous(breaks=seq(0,480,120)) +
 # scale_y_continuous(breaks=seq(0,1,.25)) +
  #expand_limits(x=c(0,480),y=c(0,1)) +
  xlab("Ordinal Day") + ylab("Cumulative Hazard Function") +
theme_classic() +
theme(axis.line.x = element_line(color = "black"),
      axis.line.y = element_line(color = "black"))



```
# Hold SIC constant at the mean and plot hazard for windspeed


```{r}

### Trial from Shane Frank email 11/5/2020

library(stringr)
library(tidyverse)

fit.one <- coxph(Surv(tstart, tstop, migrate) ~ Dist2land_3davg + Windspeed_3davg, cluster = animal, data = cox_tdc)

fit.two <- coxph(Surv(tstart, tstop, migrate) ~ Windspeed_3davg + SICsq_3davg + Dist2land_3davg, cluster = animal, data = cox_tdc)


# Extract windspeed and SICsq data from Surv object

covs <- attr(fit.one$strata, "names")
covs <-str_split(covs, ",")
covs <- data.frame(matrix(unlist(covs), nrow=length(covs), byrow=T))
colnames(covs) <- c("Windspeed_3davg", "SICsq")
covs <- covs %>%
  mutate_all(~gsub("MeanWindspeed=", "", .)) %>%
  mutate_all(~gsub("SICsq=", "", .))

covs$Windspeed <- as.numeric(covs$Windspeed)
covs$SICsq <- as.numeric(covs$SICsq)


# Bind back to tidy dataframe

tidy_model <- tidy_model %>%
  dplyr::select(-strata) %>%
  bind_cols(covs)



```

Example: How to add variables and predict over new dataframe when using time-dependent covariates

From ```{r [pammtools' Time-Dependent Covariates](https://adibender.github.io/pammtools/articles/tdcovar.html)}``` 

```{r eval= FALSE}

rm(list= ls())

library(mgcv)
library(dplyr)
library(survival)
library(pammtools)
library(ggplot2)


data("pbc", package = "survival")
head(pbc)[, c(1:5, 11, 12)]
head(pbcseq)[, c(1, 4:5, 7, 12, 13)]

pbc <- pbc %>% mutate(bili = log(bili), protime = log(protime)) # log = e^x = y; y = bili
pbcseq <- pbcseq %>% mutate(bili = log(bili), protime = log(protime))

temp <- subset(pbc, id <= 312, select = c(id:sex)) # baseline
pbc2 <- tmerge(temp, temp, id = id, death = event(time, status)) #set range
pbc2 <- tmerge(pbc2, pbcseq, id = id, bili = tdc(day, bili),
  protime = tdc(day, protime))

fit1 <- coxph(Surv(time, status == 2) ~ bili + protime, pbc)
fit2 <- coxph(Surv(tstart, tstop, death == 2) ~ bili + protime, pbc2)
rbind("baseline fit" = coef(fit1), "time dependent" = coef(fit2))


pbc <- pbc %>% filter(id <= 312) %>%
  select(id:sex, bili, protime) %>%
  mutate(status = 1L * (status == 2)) # Turns status == 2 to status == 1

pbc_ped <- as_ped( # I don't need to do this because I'm not interested in piecewise exponential data
  data = list(pbc, pbcseq),
  formula = Surv(time, status) ~ . + concurrent(bili, protime, tz_var = "day"),
  id = "id")

pbc_pam <- gam(ped_status ~ s(tend) + bili + protime, data = pbc_ped,
  family = poisson(), offset = offset)
cbind(pam = coef(pbc_pam)[2:3], cox = coef(fit2))

reference = sample_info(pbc_ped) # means for all values


bili_df <- pbc_ped %>% ungroup() %>%
  make_newdata(bili = seq_range(bili, n = 100)) %>% # everything held at average except bili
  add_term(pbc_pam, term = "bili", reference = reference) %>%
  mutate(cox = predict(fit2, ., type = "term")[, "bili"])

## Effect of protime - same thing as bili but for protime
protime_df <- pbc_ped %>% ungroup() %>%
  make_newdata(protime = seq_range(protime, n=100)) %>%
  add_term(pbc_pam, term = "protime", reference = reference) %>% # not needed when just using coxph?
  mutate(cox = predict(fit2, ., type = "term")[, "protime"])

# visualization
# remember that bili and protime are log transformed

p_term <- ggplot(data = NULL, aes(y = fit)) + geom_line(aes(col = "PAM")) +
  geom_ribbon(aes(ymin = ci_lower, ymax = ci_upper), alpha = 0.2) +
  geom_line(aes(y = cox, col = "Cox")) +
  scale_colour_manual(name = "Method", values = c("#E41A1C", "#000000"))
gridExtra::grid.arrange(
  p_term %+% bili_df + aes(x = exp(bili)),
  p_term %+% protime_df + aes(x = exp(protime)),
  nrow = 1L)
```

Attempting to follow this procedure for pb data

```{r}

library(dplyr)
library(survival)
library(pammtools)
library(ggplot2)
library(tidyverse)
library(stringr)

fit <- coxph(Surv(tstart, tstop, migrate) ~ Dist2land_3davg + Windspeed_3davg, cluster = animal, data = cox_tdc) # Model = DistSpeed3

surv_fit <- survfit(Surv(tstart, tstop, migrate) ~ Dist2land_3davg + Windspeed_3davg, cluster = animal, data = cox_tdc)

tidyfit <- broom::tidy(fit)

tidy_survfit <- broom::tidy(surv_fit)

# Extract windspeed and SICsq data from Surv object

covs <- attr(surv_fit$strata, "names")
covs <-str_split(covs, ",")
covs <- data.frame(matrix(unlist(covs), nrow=length(covs), byrow=T))
colnames(covs) <- c("Dist2land_3davg", "Windspeed_3davg")
covs <- covs %>%
  mutate_all(~gsub("Dist2land_3davg=", "", .)) %>%
  mutate_all(~gsub("Windspeed_3davg=", "", .))
 
covs$Windspeed_3davg <- as.numeric(covs$Windspeed_3davg)
covs$Dist2land_3davg <- as.numeric(covs$Dist2land_3davg)

covs <- cbind(tidy_survfit, covs)
covs <- dplyr::select(covs, -strata)
windspeed <- covs$Windspeed_3davg

cox_tdc$risk <- predict(fit, newdata = cox_tdc, type = "risk", reference = "sample", na.action = na.pass)

cox_tdc <- na.omit(cox_tdc)
cox_tdc

new <- covs %>%
  make_newdata(Windspeed_3davg = seq_range(Windspeed_3davg, n = 100)) 

new <- new %>%
  mutate(HR = predict(fit, ., type = "risk", na.action = na.pass))


  mutate(risk = predict(fit, ., type = "risk", na.action = na.pass))

ggplot(data = new) + 
  aes(x = Windspeed_3davg, y = HR) + 
  geom_line()

```

